name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  push_to_branch: "gh-pages"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Remove Build
      run: rm ./myapp

    - run: git fetch origin
    - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - run: git config --global user.name "$GITHUB_ACTOR"
    # - run: git add .
    # - run: git commit -m "push from github action"
    - run: git push origin {{env.push_to_branch}}
    # - name: Push to built gh-pages branch
    #   uses: Automattic/action-commit-to-branch@master
    #   with:
    #     branch: 'gh-pages'
    #     commit_message: 'Success Build from master'
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required
